
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Arrow_Class.Arrow(SharpGL.OpenGL,System.Single)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Arrow_Class.ArrowHeadCone(SharpGL.OpenGL,System.Single,System.Single,System.Single,System.Single)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Arrow_Class.ArrowShaftCylinder(SharpGL.OpenGL,System.Single,System.Single,System.Double,System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Axis_Class.MyGlobalAxis(SharpGL.OpenGL)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Axis_Class.MyGlobalAxis(SharpGL.OpenGL)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Grid_Class.MyGrid(SharpGL.OpenGL,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Axis_Arrow_Grid.Grid_Class.MyGrid(SharpGL.OpenGL,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:DMT01.MainWindow.myOpenGLControl_OpenGLDraw(System.Object,SharpGL.SceneGraph.OpenGLEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:DMT01.MainWindow.myOpenGLControl_OpenGLInitialized(System.Object,SharpGL.SceneGraph.OpenGLEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:DMT01.MainWindow.myOpenGLControl_Resized(System.Object,SharpGL.SceneGraph.OpenGLEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:DMT01.MainWindow.myReoGridControl_Loaded(System.Object,System.Windows.RoutedEventArgs)")]